version: '3.8'

services:
  app:
    build: .
    container_name: fastapi_app
    ports:
      - "${EXTERNAL_PORT_APP}:8000"
    command: sh -c "uvicorn main:app --host=0.0.0.0 --port=8000 --reload"
    env_file:
      - .env
    depends_on:
      - db

  db:
    image: postgres:15
    container_name: postgres_db
    environment:
      POSTGRES_USER: your_user
      POSTGRES_PASSWORD: your_password
      POSTGRES_DB: your_dbname
    ports:
      - "${EXTERNAL_PORT_DB}::5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  worker:
    build: .
    container_name: fastapi_worker
    depends_on:
      - db
    env_file:
      - .env
    command: [ "python", "-m", "rabbit.consumer" ]

volumes:
  postgres_data:
